CMakeLists.txt
src/FormatVisitor.cpp

fix CMakeLists to support vs2015.
and a little change for test project.

add win32 support

---

README.md
src/Config.cpp
src/Config.h
src/FormatVisitor.cpp
src/FormatVisitor.h
test/test_config.cpp
test/test_format_file.cpp
test/testdata/chop_down/_block.lua
test/testdata/chop_down/_parameter.lua
test/testdata/chop_down/block.lua
test/testdata/chop_down/parameter.lua
test/testdata/statement/_statements.lua
test/testdata/statement/_table.lua

- Add new config to set whether you need keep
a simple block one line

feat: keep block one line

---

docs/Style-Config.md
src/Config.cpp
src/Config.h
src/FormatVisitor.cpp
test/test_config.cpp

feat: support use_tab

---

src/FormatVisitor.cpp
test/test_format_file.cpp
test/testdata/issues/_issue-19.lua
test/testdata/issues/issue-19.lua
test/testdata/linebreak/_indent_in_explist.lua

fix: unexpected line break in args

---

src/Config.cpp
src/Config.h
src/FormatVisitor.cpp

fix: incorrect indent when use tab

---

docs/Style-Config.md
src/Config.cpp
src/Config.h
src/FormatVisitor.cpp
test/test_config.cpp

feat: support chop_down_parameter

---

README.md

chore: replace wiki link to file link

---

.gitmodules
CMakeLists.txt
README.md
src/Config.cpp
src/Config.h
src/FormatVisitor.cpp
src/lua-format.cpp
src/main.cpp
test/test_config.cpp
test/test_format_file.cpp

changed configuration handling to yaml-cpp
added a new option for dumping the default configuration

improvement: improve configuration handling

---

.travis.yml
CMakeLists.txt
README.md
appveyor.yml
src/main.cpp
test/cpp17/fs.cpp

if the user doesn't specify the config argument
it's useful to search for the file in the current directory
*before* we assume the user intends to use the default configuration.
This commits introduces a dependency on the C++ 17 standard.

feat: add automatic load of '.lua-format'

---

CMakeLists.txt
README.md

improv: improve README

---

README.md
docs/Style-Config.md
src/Config.cpp
src/FormatVisitor.cpp
test/test_format_file.cpp
test/testdata/issues/_issue-62_1.lua
test/testdata/issues/_issue-62_2.lua
test/testdata/issues/_issue-62_3.lua
test/testdata/issues/issue-62_1.config
test/testdata/issues/issue-62_1.lua
test/testdata/issues/issue-62_2.config
test/testdata/issues/issue-62_2.lua
test/testdata/issues/issue-62_3.config
test/testdata/issues/issue-62_3.lua

https://github.com/Koihik/LuaFormatter/issues/62

feature: chop_down_table option. issues/62

---

src/FormatVisitor.cpp
src/main.cpp

Fixed warnings generated by GCC.
Signed-off-by: Pedro Tammela <pctammela@gmail.com>

fix: fix warnings

---

src/main.cpp

now all fail branches should terminate the program with a exit code of 1
reported on #68

fix: add missing error returns

---

src/FormatVisitor.cpp
test/test_format_file.cpp
test/testdata/issues/_issue-70.lua
test/testdata/issues/issue-70.lua

reported on issue #70
Signed-off-by: Pedro Tammela <pctammela@gmail.com>

fix: fix segfault on varsuffix visit

---

.github/workflows/coverage.yml
.github/workflows/main.yml
.travis.yml

Coverage was broken in travis. Fix it and move to it to github actions.
Also renamed CI github action to Luarocks.

fix: fix coverage

---

.github/workflows/coverage.yml

fix: ci coverage

---

src/FormatVisitor.cpp
test/test_format_file.cpp
test/testdata/issues/_issue-80.lua
test/testdata/issues/issue-80.lua

fix: comment visit twice in some case

---

src/FormatVisitor.cpp

fixes https://github.com/Koihik/LuaFormatter/issues/91

improv: replace arg in LOG_FUNCTION_* to __func__

---

luaformatter-scm-1.rockspec

Fix LuaRocks installing in the wrong place

---

src/Config.cpp
src/Config.h
src/FormatVisitor.h
src/main.cpp

Set the configuration flags input from commandline as stated in issue#[110](https://github.com/Koihik/LuaFormatter/issues/110)

Configuration flags on the commandline

---

src/main.cpp

[fix] group validation should be "AtMostOne"

---

README.md

Added option details for the command line.

Update README.md with Configuration setting through commandline 

---

CMakeLists.txt
test/test_args.cpp

I create the first set of unit test for the feature.

Unit-test for command line feature

---

src/lua-format.cpp
test/test_format_file.cpp
test/testdata/disable_format/_simple.lua
test/testdata/disable_format/_with_indent.lua
test/testdata/disable_format/simple.lua
test/testdata/disable_format/with_indent.lua

feat: support disable format

---

src/Config.cpp
test/test_validation.cpp
test/testdata/Config/no_error_quote.config
test/testdata/Config/no_error_tab.config
test/testdata/Config/single_to_double.config
test/testdata/Config/tab.config

Implemented validators for conflicting configuration values

Conflicting Configuration Validators

---

CMakeLists.txt

fix: fix build

---

README.md

I think it would be nice to include info about disable format feature :+1:

docs: Add information about disable formatting feature

---

src/FormatVisitor.cpp
src/FormatVisitor.h
test/test_format_file.cpp
test/testdata/issues/_issue-156.lua
test/testdata/issues/issue-156.config
test/testdata/issues/issue-156.lua

fix: redundant indent of break_after_functiondef_lp

---

src/FormatVisitor.cpp
src/FormatVisitor.h
test/test_format_file.cpp
test/testdata/issues/_issue-104.lua
test/testdata/issues/_issue-162.lua
test/testdata/issues/issue-162.config
test/testdata/issues/issue-162.lua

fix: unexpected linebreak in functioncall

---

CMakeLists.txt
src/FormatVisitor.cpp
test/test_format_file.cpp
test/testdata/issues/_issue-186.lua
test/testdata/issues/issue-186.lua

fix: avoid break line before shorter explist

---

docs/Style-Config.md

- update `keep_simple_function_one_line` section
- correct spelling
- correct article agreement
- correct punctuation

(docs) update docs/Style-Config.md
