Koihik/LuaFormatter

- src/FormatVisitor.cpp
- test/test_format_file.cpp
- test/testdata/linebreak/_disable_align_in_function.lua
- test/testdata/linebreak/_functioncall.lua
- test/testdata/linebreak/disable_align_in_function.lua
fix incorrect indent in function body or table
when they are right value of assign statment
> fix: incorrect indent in function & table

- src/FormatVisitor.cpp
> fix: use space to align when use tab

- Dockerfile
A public docker image built with this Dockerfile is available at https://cloud.docker.com/u/evbfirmware/repository/docker/evbfirmware/luaformatter. This is not actively maintained per se.
> Added Dockerfile that creates image that contains LuaFormatter

- .travis.yml
- CMakeLists.txt
- README.md
- docs/Style-Config.md
- luaformatter-scm-1.rockspec
- src/Config.cpp
- src/FormatVisitor.cpp
- src/FormatVisitor.h
- src/lua-format.cpp
- src/main.cpp
- test/test_format_file.cpp
- test/testdata/literals/_doublequote.lua
- test/testdata/literals/_singlequote.lua
- test/testdata/literals/doublequote.config
- test/testdata/literals/doublequote.lua
- test/testdata/literals/singlequote.config
- test/testdata/literals/singlequote.lua
now it's possible to specify string literals preference
for example:
local foo = "a" <-> local foo = 'a'
local foo = 'don\'t' <-> local foo = "don't"
> feature: add string literal transformation

- CMakeLists.txt
- test/test_config.cpp
- test/test_format_file.cpp
- test/test_parser.cpp
Removed the use of relative paths on testing. Discussed in #63.
Signed-off-by: Pedro Tammela <pctammela@gmail.com>
> fix: don't use relative paths on tests

- README.md
- docs/Style-Config.md
- src/Config.cpp
- src/FormatVisitor.cpp
- src/FormatVisitor.h
- test/test_config.cpp
- test/test_format_file.cpp
- test/testdata/issues/issue-36.config
- test/testdata/keep_simple_block_one_line/_default.lua
- test/testdata/keep_simple_block_one_line/_keep_simple_control_block_one_line_false.lua
- test/testdata/keep_simple_block_one_line/_keep_simple_function_one_line_false.lua
- test/testdata/keep_simple_block_one_line/default.lua
- test/testdata/keep_simple_block_one_line/keep_simple_control_block_one_line_false.config
- test/testdata/keep_simple_block_one_line/keep_simple_control_block_one_line_false.lua
- test/testdata/keep_simple_block_one_line/keep_simple_function_one_line_false.config
- test/testdata/keep_simple_block_one_line/keep_simple_function_one_line_false.lua
* More granular control over "keep_simple_block_one_line".
* This should be backward compatible. 
* Note, I haven't updated README.md or other docs yet; I will do that once I get approval for this change. 
Thank you!
> Support "disable_simple_one_line_block" for specific type of code block.

- CMakeLists.txt
- README.md
mostly quality of life commits
> fix: link to stdc++fs when needed as discussed in #88

- CMakeLists.txt
Before create configuration cmake script try compile some program which required `filesystem` from 17 standard. `gcc` and `clang` required manually linking `stdc++fs` library, but in `CMakeLists.txt` the library appends only for `gcc`. So I fix that
> add support clang compiler

- src/FormatVisitor.cpp
- test/test_format_file.cpp
- test/testdata/issues/PR-100.config
- test/testdata/issues/PR-100.lua
- test/testdata/issues/_PR-100.lua
Config file
```
column_limit: 120
use_tab: true
indent_width: 1
continuation_indent_width: 1
keep_simple_control_block_one_line: false
keep_simple_function_one_line: false
align_args: false
break_after_functioncall_lp: true
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
align_parameter: false
align_table_field: false
break_after_table_lb: false
break_before_table_rb: false
chop_down_kv_table: true
chop_down_parameter: true
chop_down_table: false
table_sep: ','
extra_sep_at_table_end: true
break_after_operator: true
single_quote_to_double_quote: false
double_quote_to_single_quote: false
spaces_before_call: 0
```
Input:
```lua
-- @return new occ_token for user
function M:add_permission(admin_token, user_id, occ_token, permission) …
```
> fix bug with wrong indendation in fucntion call

- README.md
- docs/Style-Config.md
- src/Config.cpp
- src/FormatVisitor.cpp
- test/test_config.cpp
- test/test_format_file.cpp
- test/testdata/issues/_issue-98.lua
- test/testdata/issues/_issue-98_1.lua
- test/testdata/issues/issue-98.config
- test/testdata/issues/issue-98.lua
- test/testdata/issues/issue-98_1.config
- test/testdata/issues/issue-98_1.lua
by default the column_table_limit is same as column_limit.
User can set the value of column_table_limit in type int.
as discussed in [issue#98](https://github.com/Koihik/LuaFormatter/issues/98)
> fix issue#98 : adding column_table_limit feature

- README.md
- src/main.cpp
This pull request introduces a global configuration file for Linux systems located at `$XDG_CONFIG_HOME/luaformatter/config.yaml`. If not set or empty, `$XDG_CONFIG_HOME` defaults to `$HOME/.config` as specified by the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).
If this file exists, it overrides only the builtin defaults, not the `.lua-format` file. If this file does not exist or the operating system is not Linux based, the program behaves the same as before.
> Search for configuration file in XDG_CONFIG_HOME.

- docs/Style-Config.md
Fix an example in `Style-Config.md`: `indent_width`, tab character to 4 spaces as explained.
> Fix an example in Style-Config.md: indent_width

- CMakeLists.txt
- src/Config.cpp
- src/Config.h
- src/main.cpp
- test/test_validation.cpp
- test/testdata/Config/column_limit.config
- test/testdata/Config/column_table_limit.config
- test/testdata/Config/indent_width.config
- test/testdata/Config/spaces_before_call.config
configuration field value validation
> Lazy configuration validator

- src/main.cpp
If `$XDG_CONFIG_HOME` is not set, fallback to the default of `$HOME/.config` doesn't work properly, since `conf_dir` may be modified inside the previous if statement body.
> Fix configuration file fallback on Linux

- README.md
- docs/Style-Config.md
- src/Config.cpp
- src/FormatVisitor.cpp
- src/main.cpp
- test/test_config.cpp
- test/test_format_file.cpp
- test/testdata/statement/_inner_spaces.lua
- test/testdata/statement/inner_spaces.config
- test/testdata/statement/inner_spaces.lua
This PR adds four new options dealing with spacing around parenthesis, braces, and equal signs.  Defaults are set so as to not change existing default formatting.  Unit tests and documentation added for each option.
```yaml
spaces_inside_functiondef_parens:  false
spaces_inside_functioncall_parens: false
spaces_inside_table_braces:        false
spaces_around_equals_in_field:     true
```
type: `bool`, default: `false`
Inserts spaces inside the parenthesis in a function header.
```lua
-- original
function foo(x, y)
print('hello')
end
foo = function(x, y)
print('hello')
end
-- transformed
function foo( x, y )
print('hello')
end
foo = function( x, y )
print('hello')
end
```
type: `bool`, default: `false`
Inserts spaces inside the parenthesis in a function call.
```lua
-- original
function …
```
> Add Four New Spacing Options

- README.md
- docs/Style-Config.md
- src/Config.cpp
- src/FormatVisitor.cpp
- src/main.cpp
Don't ask why =) I just need it.
type: int, default: 1
Line brakes after function body
```lua
-- original(1)
function foo()
end
function foo2()
end
-- transformed(2)
function foo()
end
function foo2()
end
```
> [Feature] New format option "line_breaks_after_function_body"

- src/FormatVisitor.cpp
- test/test_config.cpp
When the `spaces_inside_functioncall_parens` option is enabled,
there is an edge case that does not work.  That is, when the
line that is formatted with the option off fits on a line, but then
when formatted with the option on, the length of the line gets
pushed just over the column limit.  In that case, the spaces are
not inserted properly.  This should fix that.
Added test case for this which fails without this fix.
> Fix bug with option spaces-inside-functioncall-parens.

- .gitattributes
- CMakeLists.txt
- README.md
- src/Config.cpp
- src/lua-format.cpp
- src/lua-format.h
- src/main.cpp
- test/test_config.cpp
- test/test_line_separator.cpp
```
Add config "line_separator" which supports the following options
input: Determine line separator by the input content. This is the default.
os: Determine line separator by the operating system
lf: Use Unix Style ("\n")
cr: Use classic Max Style ("\r")
crlf: Use Windows Style ("\r\n")
Note that the default behavior is changed.
The previous behavior is "os",
but I think "input" is a more appropriate default.
```
Some potential issues:
1. To avoid potential test issues by git autocrlf, I have modified .gitattributes to force all files to be checkouted in LF line separator.
2. The new line separator behavior is not the same as the old behavior. The old behavior determines the output line separator by the operating system (by `std::cout` in text mode). The new behavior defaults to …
> feat: support config line_separator

- src/main.cpp
Replace preprocessor directive with one that will evaluate to true on
all Unix and Apple systems.
Resolves  #176.
> Support $XDG_CONFIG_HOME on MacOS

- .editorconfig
- src/main.cpp
Hey :wave:
The functionality is more or less exactly the same as described in the issue. I also included some minor refactoring commits and added a basic `.editorconfig`. Happy to receive feedback on these changes if they are out of place or considered non-improvements.
Resolves #142.
> Implement --check option

- src/Config.h
The correct (nested) namespace after #include <experimental/filesystem>
is std::experimental::filesystem, instead of experimental::filesystem.
For reference, see:
https://stackoverflow.com/questions/48312460/c17-filesystem-is-not-a-namespace-name
> Fix namespace alias for <experimental/filesystem>

- src/FormatVisitor.cpp
- test/test_format_file.cpp
- test/testdata/issues/PR-181.config
- test/testdata/issues/PR-181.lua
- test/testdata/issues/_PR-181.lua
When `use_tab` is configured, `align_parameter` does not respect the proper alignment and instead writes as many tabs as if they were spaces, massively offsetting the second line to the right in most cases.
This change copies the behavior from `align_args` into the `align_parameter` code.
> Fixed align_parameter when using tabs

- src/Config.cpp
- src/FormatVisitor.cpp
Currently, changing `column_table_limit` changes `column_limit` as well. This is because the two options share the same node:
https://github.com/Koihik/LuaFormatter/blob/5ab5de2eab4af5241fbb2beb9eee69d039d25263/src/Config.cpp#L41
This PR introduces a special value of 0 for `column_table_limit`, in which case `column_limit` will be used instead.
While a nicer solution is definitely possible, this works well enough for this specific case, and doesn't require too many changes to the config system.
Fixes #151.
> Fix column_table_limit behavior

- src/FormatVisitor.cpp
Allow chop_down_kv_table to work even when !beyondLimit.
Fixes #195
I'm not 100% sure if this is the preferred way to fix this but for me it works.
The [documentation](https://github.com/Koihik/LuaFormatter/blob/master/docs/Style-Config.md#chop_down_kv_table) does not say that the chop_down_kv_table option should be effected by the column_limit but as [currently implemented](https://github.com/Koihik/LuaFormatter/blob/master/src/FormatVisitor.cpp#L1592) chop_down_kv_table is not checked until beyondLimit == true.
This small change seems to work for me and makes this work as documented.
If there are any changes I should make to my commit please let me know and I will be happy to make them.
Thank you!
> Minor change to chop_down_kv_table behavior

- CMakeLists.txt
Trying to compile Catch2 under Apple Silicon seems to generate the wrong
instructions. The problem does indeed lie with Catch2, but as this
affects multiple users and doesn't seem to have any drawbacks; the 
immediate fix is here (and it's outside of my knowledge as to why it fails)
Another (more preferable) idea is to just add this to the rockspec instead.
Ref #199
Ref #180
> Disable tests for Silicon

- .pre-commit-hooks.yaml
Hello! I've been working with the maintainer of [pre-commit](https://pre-commit.com/) to add official Lua support for the pre-commit tool. With pre-commit, a developer or team can choose to run hooks that will execute before a change is committed to git.
Support for Lua in pre-commit was literally added an hour ago as of this PR submission in https://github.com/pre-commit/pre-commit/pull/2158, so this change is hot off the presses.
I believe that LuaFormatter would be a fantastic tool to work with pre-commit since running a code formatter is a very common thing to do before committing.
This PR adds a hooks definition file that will allow any project to use lua-format with pre-commit. I ran a local test on one of my projects to confirm the behavior. I've included the output with no changes …
>  Add pre-commit hook to enable LuaFormatter for pre-commit.

- src/FormatVisitor.cpp
- test/lua/issues/_issue-250.lua
- test/lua/issues/issue-250.config
- test/lua/issues/issue-250.lua
This PR changes the regex replacements to only replace quotes between the quotes for the string delimiters.
This removes the need for the extra escape transformation, which fixes #250.
> Only transform quotes in characters between string delimiters

- README.md
- docs/Style-Config.md
- src/Config.cpp
- test/config/column_table_limit.config
- test/test_validation.cpp
The behavior of the `column_table_limit` configuration parameter and its default value were changed in PR #217. This broke users' configs (see #226) since the changes were not echoed to the docs and the corresponding validator wasn't updated. This PR cleans up after it.
Fixes #226.
> Update docs and validation for column_table_limit
